/**
 * 🏷️ Labels du domaine Property Approvals
 */

export const PROPERTY_APPROVALS_LABELS = {
  title: 'Approbations de propriétés',
  subtitle: 'Réviser et modérer les annonces immobilières soumises par les propriétaires.',

  table: {
    title: 'Toutes les propriétés',
    subtitle: 'Gérer les propriétés de toutes catégories avec des vues spécialisées',
    headers: {
      property: 'Propriété',
      owner: 'Propriétaire',
      location: 'Localisation',
      status: 'Statut',
      price: 'Prix',
      images: 'Images',
      createdAt: 'Créé le',
      actions: 'Actions',
    },
    unknownProperty: 'Propriété inconnue',
    untitled: 'Sans titre',
    status: {
      approved: 'Approuvé',
      rejected: 'Rejeté',
      pending: 'En attente',
    },
  },

  status: {
    all: 'Toutes',
    pending: 'En attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
  },

  tabs: {
    all: 'Toutes les propriétés',
    pending: 'En attente',
    approved: 'Approuvées',
    rejected: 'Rejetées',
  },

  actions: {
    view: 'Voir détails',
    approve: 'Approuver',
    reject: 'Rejeter',
    setPending: 'Mettre en attente',
    delete: 'Supprimer',
    edit: 'Modifier',
    export: 'Exporter vers CSV',
    addProperty: 'Ajouter une propriété',
    deleteProperty: 'Supprimer la propriété',
    viewDetails: 'Voir les détails',
    moreActions: "Plus d'actions",
  },

  bulk: {
    selected: '{{count}} propriété(s) sélectionnée(s)',
    tooltips: {
      approve: 'Approuver {{count}} propriété(s)',
      setPending: 'Mettre {{count}} propriété(s) en attente',
      reject: 'Rejeter {{count}} propriété(s)',
      clear: 'Effacer la sélection',
    },
    actions: {
      approveAll: 'Tout approuver',
      setPending: 'Mettre en attente',
      rejectAll: 'Tout rejeter',
      clear: 'Effacer',
    },
  },

  search: {
    placeholder: 'Rechercher des propriétés...',
    ariaLabel: 'filtre de statut des propriétés',
  },

  emptyState: {
    title: 'Aucune propriété trouvée',
    noMatch: 'Aucune propriété ne correspond à vos critères de recherche.',
    noProperties: "Il n'y a pas encore de propriétés dans le système.",
  },

  modals: {
    title: 'Détails de la propriété',
    ownerInfo: 'Informations propriétaire',
    ownerName: 'Nom du propriétaire',
    unknownOwner: 'Propriétaire inconnu',
    unknownAdmin: 'Administrateur inconnu',
    noEmail: "Pas d'email",
    ownerId: 'ID Propriétaire',
    basicInfo: 'Informations de base',
    amenities: 'Équipements',
    rules: 'Règles',
    availability: 'Disponibilité',
    moderationNotes: 'Notes de modération',
    sections: {
      basicInfo: 'Informations de base',
      location: 'Localisation',
      amenities: 'Équipements et fonctionnalités',
      validation: 'Statut de validation',
      availability: 'Calendrier de disponibilité',
    },
    fields: {
      propertyId: 'ID de la propriété',
      propertyTitle: 'Titre de la propriété',
      title: 'Titre',
      city: 'Ville',
      description: 'Description',
      nightlyRate: 'Tarif par nuit',
      maxCapacity: 'Capacité maximale',
      imagesCount: "Nombre d'images",
      ownerId: 'ID du propriétaire',
      createdAt: 'Créé le',
      createdDate: 'Date de création',
      updatedAt: 'Mis à jour le',
      lastUpdated: 'Dernière mise à jour',
      validationStatus: 'Statut de validation',
      validatedBy: 'Validé par',
      validatedDate: 'Date de validation',
      moderationNotes: 'Notes de modération',
      bedrooms: 'Chambres',
      bathrooms: 'Salles de bain',
      address: 'Adresse',
      postalCode: 'Code postal',
      availableAmenities: 'Équipements disponibles',
      status: 'Statut',
    },
    placeholders: {
      noTitle: 'Aucun titre fourni',
      noDescription: 'Aucune description fournie',
      priceNotSet: 'Prix non défini',
      noImages: 'Aucune image téléchargée',
      notValidated: 'Non validé',
      noModerationNotes: 'Aucune note de modération',
      noAmenitiesListed: 'Aucun équipement listé',
    },
    units: {
      perNight: '/nuit',
      guests: 'invités',
      images: 'image(s)',
    },
    calendar: {
      noPeriods: 'Aucune période de disponibilité configurée',
      periodsConfigured: '{{count}} période(s) de disponibilité configurée(s)',
      period: 'Période',
      status: 'Statut',
      reason: 'Raison',
      available: 'Disponible',
      unavailable: 'Indisponible',
      noReason: 'Aucune raison fournie',
      parseError: "Erreur lors de l'analyse des données du calendrier",
      rawData: 'Données brutes :',
      noCalendar: 'Aucun calendrier de disponibilité configuré',
    },
  },

  edit: {
    titles: {
      propertyInfo: 'Modifier les informations de la propriété',
      location: "Modifier l'emplacement",
      amenities: 'Modifier les équipements',
      adminNotes: "Notes d'administration",
    },
    fields: {
      propertyTitle: 'Titre de la propriété',
      description: 'Description',
      nightlyRate: 'Tarif par nuit (€)',
      maxCapacity: 'Capacité maximale',
      bedrooms: 'Chambres',
      bathrooms: 'Salles de bain',
      address: 'Adresse',
      city: 'Ville',
      postalCode: 'Code postal',
      addAmenity: 'Ajouter un équipement',
      moderationNotes: 'Notes de modération',
    },
    helpers: {
      title: 'Titre clair et descriptif sans majuscules excessives',
      description: 'Description précise sans coordonnées ni liens externes',
      pricing: 'Tarification adaptée au marché',
      capacity: "Limite d'occupation sécurisée",
      bedrooms: 'Chambres réelles avec intimité',
      bathrooms: 'Utiliser 0,5 pour les demi-salles de bain',
      address: "Adresse générale (éviter les numéros d'unité spécifiques pour la confidentialité)",
      city: 'Nom de ville standardisé',
      postalCode: 'Format correct pour le pays',
      moderationNotes: 'Documenter les modifications effectuées et les raisons...',
      internalNotes: 'Notes internes sur les modifications et communications',
    },
    messages: {
      noAmenities: 'Aucun équipement listé',
    },
  },

  moderation: {
    title: 'Notes de modération',
    placeholder: 'Ajouter des notes pour votre décision (optionnel)...',
    actions: {
      close: 'Fermer',
      cancel: 'Annuler',
      saveChanges: 'Enregistrer les modifications',
      saving: 'Enregistrement...',
      editProperty: 'Modifier la propriété',
      reject: 'Rejeter',
      rejecting: 'Rejet en cours...',
      setPending: 'Mettre en attente',
      settingPending: 'Mise en attente...',
      approve: 'Approuver',
      approving: 'Approbation en cours...',
    },
  },

  filters: {
    search: 'Rechercher...',
    city: 'Ville',
    country: 'Pays',
    minPrice: 'Prix minimum',
    maxPrice: 'Prix maximum',
    status: 'Statut',
  },

  messages: {
    approveSuccess: 'Propriété approuvée avec succès',
    approveError: "Erreur lors de l'approbation",
    rejectSuccess: 'Propriété rejetée avec succès',
    rejectError: 'Erreur lors du rejet',
    setPendingSuccess: 'Statut mis en attente avec succès',
    setPendingError: 'Erreur lors du changement de statut',
    deleteSuccess: 'Propriété supprimée avec succès',
    deleteError: 'Erreur lors de la suppression',
    updateSuccess: 'Propriété mise à jour avec succès',
    updateError: 'Erreur lors de la mise à jour',
    noSelection: 'Aucune propriété sélectionnée',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cette propriété ?',
    exportInProgress: 'Export en cours...',
    reviewSubtitle: 'Réviser et modérer les annonces immobilières soumises par les propriétaires.',
    loadError: 'Erreur lors du chargement des propriétés',
    noImagesAvailable: 'Aucune image disponible pour cette propriété',
  },
} as const;

export type PropertyApprovalsLabels = typeof PROPERTY_APPROVALS_LABELS;
